import { useState } from "react";
import { findBuiltInParameter } from "../../utils/builtInExpandedSelectors";
import { createEffectParameterRenderer, type ApprovedEffectEditorProps } from "./ApprovedEffectEditor";
import { InstrumentControls, InstrumentHelp, InstrumentKeyboard, InstrumentPerformanceReadout, InstrumentSection, InstrumentShell, InstrumentSlider, instrumentValue } from "./InstrumentEditorParts";
import { GuitarArticulationGuide } from "./GuitarArticulationGuide";
import { GuitarLivePerformance } from "./GuitarLivePerformance";
import "./CleanGuitarEditor.css";

function GuitarPosition({ props }: { props: ApprovedEffectEditorProps }) {
  const pickup = 455 - instrumentValue(props.schema, "pickupPosition", .15) * 130;
  const pick = 450 - instrumentValue(props.schema, "pickPosition", .2) * 190;
  return <svg className="guitar-position w-full" viewBox="0 0 580 136" role="img" aria-label="Six-string pick and pickup position schematic"><title>Position guide, not live note or string allocation</title><rect className="guitar-neck" x="42" y="22" width="508" height="88" rx="5" />{[92, 143, 187, 227, 263, 296, 326, 353, 378, 401, 422, 442, 460, 477, 493, 508].map(x => <path key={x} className="guitar-fret" d={`M${x} 23V109`} />)}{["E", "B", "G", "D", "A", "E"].map((name, i) => <g key={i}><text x="17" y={34 + i * 14}>{name}</text><path className="guitar-string" d={`M42 ${30 + i * 14}H550`} /></g>)}<rect className="guitar-pickup" x={pickup} y="18" width="14" height="95" rx="3" /><path className="guitar-pick" d={`M${pick} 4l-7 10h14Z`} /><text x="42" y="130">NUT</text><text x="484" y="130">BRIDGE</text><text x="212" y="130">PICK / PICKUP POSITION</text></svg>;
}
export function CleanGuitarEditor(props: ApprovedEffectEditorProps) {
  const [tab, setTab] = useState("Play");
  const control = createEffectParameterRenderer(props), v = (id: string) => instrumentValue(props.schema, id);
  const plucked = v("stringEngine") >= .5, articulation = findBuiltInParameter(props.schema, "articulation"), style = Math.round(v("articulation"));
  return <InstrumentShell props={props} kind="guitar" tabs={["Play", "Pick & body", "Chorus & MIDI"]} tab={tab} onTab={setTab}
    footer={<><InstrumentPerformanceReadout props={props} /><InstrumentKeyboard address={props.address} output={<InstrumentSlider props={props} id="outputGain" label="Output · dB" />} /></>}>
    {tab === "Play" && <div className="guitar-play-layout grid gap-[12px]"><InstrumentSection title="Articulation" detail="Panel setting · next notes"><div className="guitar-articulations flex flex-col gap-2" role="group" aria-label="Guitar articulation">
      {articulation?.enumOptions?.map(option => <button key={option.value} type="button" disabled={!plucked} aria-pressed={style === option.value} onClick={() => { props.onGestureStart(articulation.id); props.onChange(articulation, option.value); props.onGestureEnd(); }}><span>{option.label}</span><small>{v("articulationKeys") >= .5 ? `MIDI ${24 + option.value}` : String(option.value + 1).padStart(2, "0")}</small></button>)}
    </div>{!plucked && <InstrumentHelp>Choose Plucked loop to use articulation controls.</InstrumentHelp>}</InstrumentSection>
      <InstrumentSection title="String & tone">{control("model", false, "Instrument")}<GuitarPosition props={props} /><InstrumentControls>{control("tone")}{plucked ? <>{control("stringDecay", false, "String decay")}{control("stringDamping", false, "Damping")}{control("palmMute")}</> : control("body")}</InstrumentControls><div className="mt-5"><InstrumentControls>{control("releaseMs")}{plucked && style === 2 && control("harmonicNode")}{plucked && [4, 5, 6].includes(style) && control("slideTime")}</InstrumentControls></div></InstrumentSection>
      <InstrumentSection title="Performance">{control("stringEngine")}{control("articulationKeys", false, "MIDI keyswitches")}<div className="my-4">{control("stringMode", false, "String assignment")}</div><InstrumentControls>{control("bendRangeSemitones", false, "Bend range")}</InstrumentControls><GuitarLivePerformance articulationNames={articulation?.enumOptions?.map(option => option.label) ?? []} /><InstrumentHelp>Keyswitches override the next articulation on their MIDI channel until Reset Controllers. Live strings show the articulation used by each allocated voice, including voices still releasing.</InstrumentHelp><details className="mt-4 text-xs"><summary className="cursor-pointer py-2">Playing articulations</summary><GuitarArticulationGuide schema={props.schema} /></details></InstrumentSection>
    </div>}
    {tab === "Pick & body" && <div className="guitar-two-columns grid gap-[14px]"><InstrumentSection title="Excitation & pickup"><GuitarPosition props={props} /><InstrumentControls>{control("pickPosition")}{control("pickHardness")}{control("pickupPosition", false, "Pickup")}{control("pickNoise")}</InstrumentControls>{!plucked && <InstrumentHelp>Pick position, hardness and pickup apply to new Plucked loop voices. Pick noise remains available in the legacy voice.</InstrumentHelp>}</InstrumentSection><InstrumentSection title="Body resonance"><InstrumentControls>{control("body")}{control("coupledBody")}{control("bodyCoupling", false, "Coupling")}{control("bodyDecay")}</InstrumentControls><InstrumentHelp>Coupled body adds a secondary resonant network to either voice engine. Amount zero retains the original response.</InstrumentHelp></InstrumentSection></div>}
    {tab === "Chorus & MIDI" && <div className="guitar-two-columns grid gap-[14px]"><InstrumentSection title="Stereo chorus"><InstrumentControls>{control("chorusMix", false, "Mix")}{control("chorusRate", false, "Rate")}{control("chorusDepth", false, "Depth")}</InstrumentControls><div className="mt-5"><InstrumentSlider props={props} id="chorus" label="Stereo motion" /></div><InstrumentHelp>Delay chorus and the original stereo motion remain separate controls.</InstrumentHelp></InstrumentSection><InstrumentSection title="Performance routing">{control("stringMode", false, "String assignment")}<div className="my-4">{control("articulationKeys", false, "MIDI keyswitches")}</div><InstrumentControls>{control("bendRangeSemitones")}{control("releaseMs")}</InstrumentControls><InstrumentHelp>Keyswitches use MIDI 24–32. Pedals and per-channel bend are received from the track's MIDI input.</InstrumentHelp></InstrumentSection></div>}
  </InstrumentShell>;
}
