import { useState } from "react";
import { createEffectParameterRenderer, type ApprovedEffectEditorProps } from "./ApprovedEffectEditor";
import { InstrumentControls, InstrumentHelp, InstrumentKeyboard, InstrumentPerformanceReadout, InstrumentSection, InstrumentShell, InstrumentSlider, instrumentValue } from "./InstrumentEditorParts";
import "./PianoEditor.css";

function PianoDrawing() {
  return <svg className="piano-drawing w-full" viewBox="0 0 370 168" role="img" aria-label="Piano string and soundboard illustration"><title>Original synthesized instrument illustration</title><path className="piano-body" d="M28 142V45Q28 22 51 22H147Q170 22 192 47Q219 76 299 53Q335 44 343 72L343 142Z" /><path className="piano-interior" d="M40 132V48Q40 34 54 34H144Q165 34 184 57Q219 91 302 65Q328 58 330 78V132Z" />{Array.from({ length: 22 }, (_, i) => <path key={i} className="piano-string" d={`M${54 + i * 12} 130V${43 + (i > 8 ? Math.sin((i - 8) / 13 * Math.PI) * 35 : 0)}`} />)}<path className="piano-bridge" d="M60 113Q157 93 188 105T315 82" /><rect className="piano-keybed" x="28" y="139" width="315" height="14" rx="2" />{Array.from({ length: 27 }, (_, i) => <path key={i} className="piano-keyline" d={`M${35 + i * 11.2} 140V152`} />)}</svg>;
}
function TouchCurve({ value }: { value: number }) {
  return <svg className="piano-touch-curve w-full" viewBox="0 0 300 122" role="img" aria-label="Velocity response curve"><path className="instrument-gridline" d="M20 10V99H288 M20 55H288 M154 10V99" /><path className="piano-touch-reference" d="M20 99L288 10" /><path className="instrument-curve" d={Array.from({ length: 51 }, (_, i) => `${i ? "L" : "M"}${20 + i / 50 * 268} ${99 - (i / 50) ** (2 ** value) * 89}`).join(" ")} /><text x="20" y="118">Soft touch</text><text x="220" y="118">Hard touch</text></svg>;
}
export function PianoEditor(props: ApprovedEffectEditorProps) {
  const [tab, setTab] = useState("Instrument");
  const control = createEffectParameterRenderer(props), expressive = instrumentValue(props.schema, "performanceMode") >= .5;
  const touch = <TouchCurve value={expressive ? instrumentValue(props.schema, "velocityCurve") : 0} />;
  return <InstrumentShell props={props} kind="piano" tabs={["Instrument", "Performance", "Resonance"]} tab={tab} onTab={setTab}
    footer={<><InstrumentPerformanceReadout props={props} piano /><InstrumentKeyboard address={props.address} piano output={<InstrumentSlider props={props} id="outputGain" label="Output · dB" />} /></>}>
    {tab === "Instrument" && <div className="piano-instrument-layout grid gap-[12px]"><InstrumentSection title="Instrument" className="piano-identity">{control("model", false, "Piano model")}<PianoDrawing /><div className="piano-signature flex items-center gap-3"><strong>03</strong><span>VOICINGS<small>Original synthesized piano</small></span></div></InstrumentSection>
      <InstrumentSection title="Voicing" detail="Musical character"><InstrumentControls>{["tone", "body", "hammer", "resonance", "releaseMs", "stereoWidth"].map(id => control(id))}</InstrumentControls></InstrumentSection>
      <InstrumentSection title="Touch" detail="Performance response">{control("performanceMode")}{touch}{expressive ? <div className="flex flex-col gap-4"><InstrumentSlider props={props} id="velocityCurve" /><InstrumentSlider props={props} id="strikeColour" /></div> : <InstrumentHelp>Legacy playing retains its original response. Select Expressive for velocity timbre, release velocity and continuous pedals.</InstrumentHelp>}</InstrumentSection>
    </div>}
    {tab === "Performance" && <div className="piano-two-columns grid gap-[14px]"><InstrumentSection title="Expressive playing">{control("performanceMode")}{touch}<InstrumentControls>{["velocityCurve", "strikeColour", "releaseVelocity"].map(id => control(id))}</InstrumentControls>{!expressive && <InstrumentHelp>These settings are retained. Select Expressive to apply them to new notes.</InstrumentHelp>}</InstrumentSection><InstrumentSection title="Pedal response"><InstrumentControls>{control("damperCurve")}{control("softPedalDepth")}</InstrumentControls><div className="piano-explainer mt-6 p-[17px]"><h4>Half-pedaling</h4><p>CC64 changes damper response continuously. Sostenuto (CC66) captures already held keys. The soft pedal (CC67) changes the strike.</p></div><InstrumentHelp>Incoming controller values appear below. Performance mode is latched when each note starts.</InstrumentHelp></InstrumentSection></div>}
    {tab === "Resonance" && <div className="piano-two-columns grid gap-[14px]"><InstrumentSection title="Coupled resonance" detail="Secondary body network"><PianoDrawing /><InstrumentControls>{control("coupledBody", false, "Amount")}{control("bodyCoupling", false, "Coupling")}{control("bodyDecay")}</InstrumentControls></InstrumentSection><InstrumentSection title="Resonance & release"><InstrumentControls>{control("resonance")}{control("releaseMs")}</InstrumentControls><div className="piano-explainer mt-6 p-[17px]"><h4>Set the instrument in motion</h4><p>Coupled body adds a secondary resonance network. Held keys and pedals change its damping. At zero, the original voice remains unchanged.</p></div><InstrumentHelp>This is a synthesized instrument. No sampled library or microphone positions are implied.</InstrumentHelp></InstrumentSection></div>}
  </InstrumentShell>;
}
