if(NOT CONFIG STREQUAL "ASan")
    return()
endif()
get_filename_component(compiler_dir "${COMPILER}" DIRECTORY)
set(runtime "${compiler_dir}/clang_rt.asan_dynamic-x86_64.dll")
if(NOT EXISTS "${runtime}")
    message(FATAL_ERROR "The selected compiler's x64 ASan runtime is missing: ${runtime}. Install its ASan component before running this diagnostic configuration.")
endif()
file(COPY "${runtime}" DESTINATION "${DESTINATION}")
