param(
    [Parameter(Mandatory = $false)]
    [string]$Version = "1.24.4",

    [Parameter(Mandatory = $false)]
    [ValidateSet("win-x64")]
    [string]$Platform = "win-x64",

    [Parameter(Mandatory = $false)]
    [string]$Destination = "thirdparty/onnxruntime",

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$destinationPath = Join-Path $repoRoot $Destination
$headerPath = Join-Path $destinationPath "include/onnxruntime_cxx_api.h"
$dllPath = Join-Path $destinationPath "lib/onnxruntime.dll"

if (-not $Force -and (Test-Path $headerPath) -and (Test-Path $dllPath)) {
    Write-Host "ONNX Runtime $Version for $Platform is already installed at $destinationPath"
    exit 0
}

$assetName = "onnxruntime-$Platform-$Version.zip"
$downloadUrl = "https://github.com/microsoft/onnxruntime/releases/download/v$Version/$assetName"
$downloadRoot = Join-Path $env:TEMP "openstudio-onnxruntime-$Version-$Platform"
$archivePath = Join-Path $downloadRoot $assetName
$extractRoot = Join-Path $downloadRoot "extract"

if (Test-Path $downloadRoot) {
    Remove-Item -LiteralPath $downloadRoot -Recurse -Force
}

New-Item -ItemType Directory -Path $downloadRoot | Out-Null

Write-Host "Downloading $assetName from $downloadUrl"
Invoke-WebRequest -Uri $downloadUrl -OutFile $archivePath

Write-Host "Extracting ONNX Runtime package"
Expand-Archive -LiteralPath $archivePath -DestinationPath $extractRoot -Force

$packageRoot = Get-ChildItem -LiteralPath $extractRoot -Directory | Select-Object -First 1
if (-not $packageRoot) {
    throw "Could not find the extracted ONNX Runtime package root in $extractRoot"
}

$requiredPaths = @(
    (Join-Path $packageRoot.FullName "include/onnxruntime_cxx_api.h"),
    (Join-Path $packageRoot.FullName "lib/onnxruntime.dll"),
    (Join-Path $packageRoot.FullName "lib/onnxruntime.lib")
)

foreach ($requiredPath in $requiredPaths) {
    if (-not (Test-Path $requiredPath)) {
        throw "Required ONNX Runtime file is missing from the downloaded package: $requiredPath"
    }
}

if (Test-Path $destinationPath) {
    Remove-Item -LiteralPath $destinationPath -Recurse -Force
}

New-Item -ItemType Directory -Path $destinationPath | Out-Null

Copy-Item -LiteralPath (Join-Path $packageRoot.FullName "include") -Destination (Join-Path $destinationPath "include") -Recurse
Copy-Item -LiteralPath (Join-Path $packageRoot.FullName "lib") -Destination (Join-Path $destinationPath "lib") -Recurse

$metadataFiles = @(
    "LICENSE",
    "LICENSE.txt",
    "ThirdPartyNotices.txt",
    "README.md"
)

foreach ($metadataFile in $metadataFiles) {
    $sourcePath = Join-Path $packageRoot.FullName $metadataFile
    if (Test-Path $sourcePath) {
        Copy-Item -LiteralPath $sourcePath -Destination (Join-Path $destinationPath $metadataFile) -Force
    }
}

Write-Host "ONNX Runtime installed to $destinationPath"
Write-Host "This directory remains ignored by git and can be regenerated by rerunning this script."
