param(
    [Parameter(Mandatory = $false)]
    [string]$Ref = "496a0765b8bb9c26f764f22f9a9712a937177db2",

    [Parameter(Mandatory = $false)]
    [string]$Destination = "thirdparty/asio",

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$destinationPath = Join-Path $repoRoot $Destination
$headerPath = Join-Path $destinationPath "common/iasiodrv.h"
$hostPath = Join-Path $destinationPath "host/pc/asiolist.cpp"

if (-not $Force -and (Test-Path $headerPath) -and (Test-Path $hostPath)) {
    Write-Host "ASIO SDK is already installed at $destinationPath"
    exit 0
}

$archiveName = "asio-$Ref.zip"
$downloadUrl = "https://github.com/audiosdk/asio/archive/$Ref.zip"
$downloadRoot = Join-Path $env:TEMP "openstudio-asio-$Ref"
$archivePath = Join-Path $downloadRoot $archiveName
$extractRoot = Join-Path $downloadRoot "extract"

if (Test-Path $downloadRoot) {
    Remove-Item -LiteralPath $downloadRoot -Recurse -Force
}

New-Item -ItemType Directory -Path $downloadRoot | Out-Null

Write-Host "Downloading ASIO SDK from $downloadUrl"
Invoke-WebRequest -Uri $downloadUrl -OutFile $archivePath

Write-Host "Extracting ASIO SDK package"
Expand-Archive -LiteralPath $archivePath -DestinationPath $extractRoot -Force

$packageRoot = Get-ChildItem -LiteralPath $extractRoot -Directory | Select-Object -First 1
if (-not $packageRoot) {
    throw "Could not find the extracted ASIO SDK package root in $extractRoot"
}

$requiredPaths = @(
    (Join-Path $packageRoot.FullName "common/iasiodrv.h"),
    (Join-Path $packageRoot.FullName "host/asiodrivers.cpp"),
    (Join-Path $packageRoot.FullName "host/pc/asiolist.cpp")
)

foreach ($requiredPath in $requiredPaths) {
    if (-not (Test-Path $requiredPath)) {
        throw "Required ASIO SDK file is missing from the downloaded package: $requiredPath"
    }
}

if (Test-Path $destinationPath) {
    Remove-Item -LiteralPath $destinationPath -Recurse -Force
}

New-Item -ItemType Directory -Path $destinationPath | Out-Null

$copyItems = @(
    "common",
    "host",
    "LICENSE.txt",
    "README.md",
    "changes.txt",
    "Steinberg ASIO Licensing Agreement.pdf",
    "Steinberg ASIO SDK 2.3.pdf",
    "Steinberg ASIO Usage Guidelines.pdf"
)

foreach ($item in $copyItems) {
    $sourcePath = Join-Path $packageRoot.FullName $item
    if (Test-Path $sourcePath) {
        Copy-Item -LiteralPath $sourcePath -Destination (Join-Path $destinationPath $item) -Recurse -Force
    }
}

Write-Host "ASIO SDK installed to $destinationPath"
Write-Host "This directory remains ignored by git and can be regenerated by rerunning this script."
