#pragma once
inline juce::var checkIRSourceBlend()
{
    auto* result=new juce::DynamicObject();result->setProperty("plugin","True-stereo recorded-source interpolation");bool endpoints=true,ignored=true;double matrixError=0,renderError=0,partitionError=0;
    juce::AudioBuffer<float> canonical(4,2400);canonical.clear();canonical.setSample(0,31,.4f);canonical.setSample(1,59,-.2f);canonical.setSample(2,83,.3f);canonical.setSample(3,113,.1f);
    for(const int order:{0,1})for(const double left:{0.0,.25,.5,1.0})for(const double right:{0.0,.5,.75,1.0})
    {
        auto source=canonical;if(order==1)for(int i=0;i<source.getNumSamples();++i){const float value=source.getSample(1,i);source.setSample(1,i,source.getSample(2,i));source.setSample(2,i,value);}auto edited=source;BuiltInIRSourceBlend::apply(edited,order,left,right);
        for(int ch=0;ch<4;++ch)for(int i=0;i<source.getNumSamples();++i)
        {
            const int canonicalChannel=order==1&&ch==1?2:order==1&&ch==2?1:ch;const int output=canonicalChannel%2;const double blend=canonicalChannel<2?left:right;
            const double expected=(1-blend)*canonical.getSample(output,i)+blend*canonical.getSample(2+output,i);matrixError=juce::jmax(matrixError,std::abs(edited.getSample(ch,i)-expected));if(left==0&&right==1)endpoints=endpoints&&edited.getSample(ch,i)==source.getSample(ch,i);
        }
    }
    juce::AudioBuffer<float> stereo(2,200);for(int ch=0;ch<2;++ch)for(int i=0;i<200;++i)stereo.setSample(ch,i,static_cast<float>(i)*.001f);auto copyStereo=stereo;BuiltInIRSourceBlend::apply(copyStereo,0,.5,.5);for(int ch=0;ch<2;++ch)for(int i=0;i<200;++i)ignored=ignored&&copyStereo.getSample(ch,i)==stereo.getSample(ch,i);
    const auto file=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("openstudio-source-blend-"+juce::Uuid().toString()+".wav");auto source=std::make_unique<OpenStudioReverb>(true);source->selectAlgorithm(7);bool portable=writeProbeWave(file,canonical,48000)&&source->convolutionSpace.loadFile(file);file.deleteFile();juce::ValueTree original("Original");source->convolutionSpace.save(original);
    auto* values=new juce::DynamicObject();values->setProperty("sourceBlendLeft",.25);values->setProperty("sourceBlendRight",.75);values->setProperty("normalise",false);values->setProperty("crossTerms",.4);portable=source->convolutionSpace.edit(juce::var(values))&&portable;juce::ValueTree state("State");source->convolutionSpace.save(state);portable=portable&&state["irData"]==original["irData"];
    auto expected=canonical;BuiltInIRSourceBlend::apply(expected,0,.25,.75);expected.applyGain(1,0,expected.getNumSamples(),.4f);expected.applyGain(2,0,expected.getNumSamples(),.4f);
    const auto render=[&](int block,int input){BuiltInConvolution c;portable=c.restore(state)&&portable;c.prepare(48000,block);juce::AudioBuffer<float> output(2,3000),buffer(2,block);for(int start=0;start<3000;start+=block){const int count=juce::jmin(block,3000-start);buffer.setSize(2,count,false,false,true);buffer.clear();if(start==0)buffer.setSample(input,0,.1f);c.process(buffer,0,20,20000,1,true,false);for(int ch=0;ch<2;++ch)output.copyFrom(ch,start,buffer,ch,0,count);}return output;};
    for(int input=0;input<2;++input){const auto a=render(127,input),b=render(512,input);for(int ch=0;ch<2;++ch)for(int i=0;i<a.getNumSamples();++i){const double target=i<expected.getNumSamples()?expected.getSample(input*2+ch,i)*.1:0;renderError=juce::jmax(renderError,std::abs(a.getSample(ch,i)-target));partitionError=juce::jmax(partitionError,std::abs(static_cast<double>(a.getSample(ch,i)-b.getSample(ch,i))));}}
    juce::MemoryBlock saved,again;source->getStateInformation(saved);auto copy=std::make_unique<OpenStudioReverb>(true);copy->setStateInformation(saved.getData(),static_cast<int>(saved.getSize()));copy->getStateInformation(again);bool recall=saved==again&&static_cast<double>(copy->convolutionSpace.info()["shape"]["sourceBlendLeft"])==.25&&static_cast<double>(copy->convolutionSpace.info()["shape"]["sourceBlendRight"])==.75;
    auto tree=juce::ValueTree::readFromData(saved.getData(),saved.getSize());const auto shapeVar=tree["irShape"];const auto* bytes=shapeVar.getBinaryData();auto oldShape=juce::ValueTree::readFromData(bytes->getData(),bytes->getSize());oldShape.removeProperty("sourceBlendLeft",nullptr);oldShape.removeProperty("sourceBlendRight",nullptr);juce::MemoryBlock oldShapeBytes;{juce::MemoryOutputStream stream(oldShapeBytes,false);oldShape.writeToStream(stream);}tree.setProperty("irShape",juce::var(oldShapeBytes),nullptr);juce::MemoryBlock old;{juce::MemoryOutputStream stream(old,false);tree.writeToStream(stream);}copy->setStateInformation(old.getData(),static_cast<int>(old.getSize()));recall=recall&&static_cast<double>(copy->convolutionSpace.info()["shape"]["sourceBlendLeft"])==0&&static_cast<double>(copy->convolutionSpace.info()["shape"]["sourceBlendRight"])==1;
    auto* bad=new juce::DynamicObject();bad->setProperty("sourceBlendRight",1.1);const bool invalid=!source->convolutionSpace.edit(juce::var(bad));juce::MemoryBlock after;source->getStateInformation(after);recall=recall&&after==saved;
    result->setProperty("pass",endpoints&&ignored&&matrixError<1e-7&&renderError<2e-6&&partitionError<2e-6&&portable&&recall&&invalid);result->setProperty("defaultExactParity",endpoints);result->setProperty("monoStereoUnchanged",ignored);result->setProperty("bothChannelOrdersMaximumError",matrixError);result->setProperty("renderMatrixAndCrossTermsError",renderError);result->setProperty("partitionMaximumError",partitionError);result->setProperty("portableOriginalBytes",portable);result->setProperty("stateLegacyDefaults",recall);result->setProperty("invalidRejected",invalid);result->setProperty("schema",describeFreePluginForRegression(*source));result->setProperty("audioQuality","not_asserted");result->setProperty("geometricSourceRelocation","not_asserted; interpolation between captured columns only");return result;
}
